# Generated by Django 4.1.5 on 2023-01-12 15:02

import blogs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=blogs.models.NameField(max_length=500, unique=True),
        ),
    ]
